kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  creationTimestamp: null
  labels:
    fdk.service: rabbitmq-claim1
  name: rabbitmq-claim1
  namespace: {{ required "Missing value NAMESPACE" .Values.NAMESPACE }}
spec:
        storageClassName: ""
        volumeName: {{ required "Missing value FDK_RABBITMQ_VOLUMENAME" .Values.FDK_RABBITMQ_VOLUMENAME }}
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: {{ required "Missing value FDK_RABBITMQ_STORAGESIZE" .Values.FDK_RABBITMQ_STORAGESIZE }}
status: {}
---
kind: PersistentVolume
apiVersion: v1
metadata:
  name: {{ required "Missing value FDK_RABBITMQ_VOLUMENAME" .Values.FDK_RABBITMQ_VOLUMENAME }}
  namespace: {{ required "Missing value NAMESPACE" .Values.NAMESPACE }}
spec:
  storageClassName: ""
  capacity:
    storage: {{ required "Missing value FDK_RABBITMQ_STORAGESIZE" .Values.FDK_RABBITMQ_STORAGESIZE }}
  accessModes:
    - ReadWriteOnce
  gcePersistentDisk:
    pdName: {{ required "Missing value FDK_RABBITMQ_VOLUMENAME" .Values.FDK_RABBITMQ_VOLUMENAME }}
    fsType: ext4
